services:
  - type: web
    name: type-backend
    env: python
    region: oregon
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
